#include "types.h"
// Data declarations

// extern _UNKNOWN UiSoundCallback; weak
// extern _UNKNOWN UiMessageBoxCallback; weak
// extern _UNKNOWN UiDrawDescCallback; weak
// extern _UNKNOWN UiCreateGameCallback; weak
// extern _UNKNOWN UiArtCallback; weak
// extern _UNKNOWN SNetUnregisterEventHandler; weak
// extern _UNKNOWN SNetRegisterEventHandler; weak
extern char byte_4B4030[];
extern int dword_4B4038[4];
extern ItemDataStruct AllItemsList[119];
extern PLStruct PL_Prefix[74];
extern PLStruct PL_Suffix[101];
extern UItemStruct UniqueItemList[11];
extern char progress_bar_colours[8];
extern int progress_bar_screen_pos[3][2];
extern int AP2x2Tbl[10];
extern InvXY InvRect[73];
extern char monster_action_sounds[8];
extern char lfontframe[128];
extern char lfontkern[56];
extern char SPATS[37][7];
extern char BSTYPES[206];
extern char L5BTYPES[208];
extern BYTE STAIRSUP[34];
extern BYTE L5STAIRSUP[34];
extern BYTE STAIRSDOWN[26];
extern BYTE LAMPS[10];
extern BYTE PWATERIN[18];
extern int nummtypes;
extern int MWVel[24][3];
extern int Xmonsterhpscale[8];
extern char animletter[];
extern int left[8];
extern int right[8];
extern int opposite[8];
extern int offset_x[8];
extern int offset_y[8];
extern void (__fastcall *AiProc[23])(int);
extern char aDderrUnknown0x[19];
extern char aDserrUnknown0x[19];
extern char *off_4BB308[11];
extern char *off_4BB328[3];
extern char *off_4BB338[7];
extern char *off_4BB340[5];
extern char *off_4BB34C[2];
extern char *off_4BB350;
extern char *off_4BB358[9];
extern char *off_4BB370[3];
extern char *off_4BB380[3];
extern char *off_4BB390[5];
extern char *off_4BB3A0;
extern char *off_4BB3A8[15];
extern char *off_4BB3B0[13];
extern char *off_4BB3D8[3];
extern char *off_4BB3E8[23];
extern char *off_4BB3F0[21];
extern char *off_4BB3F8[19];
extern char *off_4BB400[17];
extern char *off_4BB408[15];
extern char *off_4BB410[13];
extern char *off_4BB414[12];
extern char *off_4BB418[11];
extern char *off_4BB41C[10];
extern char *off_4BB420[9];
extern char *off_4BB430[5];
extern char *off_4BB438[3];
extern char *off_4BB448[21];
extern char *Xqtexts[];
extern int qscroll_spd_tbl[28];
extern char mfontframe[128];
extern char mfontkern[56];
extern char path_directions[9];
extern char gbSndInited;
extern char gbMusicOn;
extern char gbSoundOn;
extern int sglMusicVolume;
extern int value;
extern int sgpMusicTrack;
extern char *sgszMusicTracks[6];
extern IDirectSoundBuffer *sglpDSB;
extern char fontframe[49];
extern char byte_4C0471[79];
extern char fontkern[72];
extern int lineoffset[5][5];
extern int spselflag;
extern char SpellITbl[40];
extern int PanBtnPos[8][5];
extern char *PanBtnStr[8];
extern int attribute_inc_rects[4][4];
extern int SpellPages[6][7];
extern char empty_string_0[];
extern HANDLE sghThread;
extern int dword_4C104C;
extern int sgbNetInited;
extern HANDLE hFile;
extern int oil_4C3328[10];
extern int oil_4C3350_ivalue[10];
extern int oil_4C3378_id[10];
extern char Xoil_names[10][25];
extern BYTE ItemCAnimTbl[160];
extern char *ItemDropStrs[31];
extern BYTE ItemAnimLs[32];
extern int ItemDropSnds[32];
extern int psfx[32];
extern int premiumlvladd[6];
extern _object_id ObjTypeConv[108];
extern ObjDataStruct AllObjects[80];
extern char *ObjMasterLoadList[44];
extern int killed_mom_parent;
extern char byte_4C56B8;
extern char empty_string_1;
extern char empty_string_2;
extern CHAR Parameters[];
extern MissileData missiledata[65];
extern MisFileData misfiledata[39];
extern int SStringY[24];
extern BYTE SkelKingTrans1[12];
extern BYTE SkelKingTrans2[8];
extern BYTE SkelKingTrans3[20];
extern BYTE SkelKingTrans4[28];
extern BYTE SkelChamTrans1[20];
extern BYTE SkelChamTrans2[8];
extern BYTE SkelChamTrans3[36];
extern int pfile_4C922C_count;
extern int dword_4C9230;
extern int lightflag;
extern char CrawlTable[2749];
extern BYTE vCrawlTable[23][30];
extern BYTE RadiusAdj[23];
extern int nTrack;
extern int XDirAdd[];
extern int YDirAdd[8];
extern MonsterData monsterdata[110];
extern char MonstAvailTbl[112];
extern UniqMonstStruct UniqMonst[33];
extern int dword_4D0B78;
extern char *gszHelpText[303];
extern char AnimOrder[6][70];
extern int TownCowX[4];
extern int TownCowY[4];
extern int TownCowDir[4];
extern int cowoffx[8];
extern int cowoffy[8];
extern char msgcnt;
extern int bxadd[8];
extern int byadd[8];
extern char *shrinestrs[13];
extern TMenuItem XsgSingleMenu_dead[6];
extern TMenuItem sgSingleMenu[5];
extern TMenuItem XsgMultiMenu_dead[4];
extern TMenuItem sgMultiMenu[5];
extern TMenuItem sgOptionMenu[5];
extern char *music_toggle_names[2];
extern char *sound_toggle_names[2];
extern int sfx_stream;
extern TSFX sgSFX[225];
extern SpellData spelldata[37];
extern int plrxoff[10];
extern int plryoff[10];
extern int plrxoff2[10];
extern int plryoff2[10];
extern char WepChar[16];
extern char PlrGFXAnimLens[3][11];
extern int PWVel[4][3];
extern int StrengthTbl[4];
extern int MagicTbl[4];
extern int DexterityTbl[4];
extern int VitalityTbl[4];
extern int ToBlkTbl[4];
extern int MaxStats[3][4];
extern int ExpLvlsTbl[51];
extern QuestData questlist[11];
extern char questxoff[8];
extern char questyoff[8];
extern int TownDownList[12];
extern int TownWarp1List[14];
extern int L1UpList[12];
extern int L1DownList[10];
extern int L2UpList[4];
extern int L2DownList[6];
extern int L2TWarpUpList[4];
extern int L3UpList[16];
extern int L3DownList[9];
extern int Area_Min;
extern int Room_Max;
extern int Room_Min;
extern signed int Dir_Xadd[5];
extern signed int Dir_Yadd[5];
extern char SPATSL2[2][7];
extern char BTYPESL2[161];
extern char BSTYPESL2[161];
extern unsigned __int8 byte_4D9FC8;
extern unsigned __int8 byte_4D9FE0;
extern unsigned __int8 byte_4D9FF8;
extern unsigned __int8 byte_4DA010;
extern unsigned __int8 byte_4DA028;
extern unsigned __int8 byte_4DA040;
extern unsigned __int8 byte_4DA058;
extern unsigned __int8 byte_4DA070;
extern unsigned __int8 byte_4DA088;
extern unsigned __int8 byte_4DA0A0;
extern unsigned __int8 byte_4DA0B8;
extern unsigned __int8 byte_4DA0D0;
extern unsigned __int8 byte_4DA0E8;
extern unsigned __int8 byte_4DA100;
extern unsigned __int8 byte_4DA118;
extern unsigned __int8 byte_4DA130;
extern unsigned __int8 byte_4DA148;
extern unsigned __int8 byte_4DA158;
extern unsigned __int8 byte_4DA168;
extern unsigned __int8 byte_4DA178;
extern unsigned __int8 byte_4DA188;
extern unsigned __int8 byte_4DA198;
extern unsigned __int8 byte_4DA1A8;
extern unsigned __int8 byte_4DA1B8;
extern unsigned __int8 byte_4DA1C8;
extern unsigned __int8 byte_4DA1E0;
extern unsigned __int8 byte_4DA1F8;
extern unsigned __int8 byte_4DA210;
extern unsigned __int8 byte_4DA228;
extern unsigned __int8 byte_4DA240;
extern unsigned __int8 byte_4DA258;
extern unsigned __int8 byte_4DA270;
extern unsigned __int8 byte_4DA288;
extern unsigned __int8 byte_4DA2A0;
extern unsigned __int8 byte_4DA2B8;
extern unsigned __int8 byte_4DA2D0;
extern unsigned __int8 byte_4DA2E8;
extern unsigned __int8 byte_4DA300;
extern unsigned __int8 byte_4DA318;
extern unsigned __int8 byte_4DA330;
extern unsigned __int8 byte_4DA348;
extern unsigned __int8 byte_4DA358;
extern unsigned __int8 byte_4DA368;
extern unsigned __int8 byte_4DA378;
extern unsigned __int8 byte_4DA388;
extern unsigned __int8 byte_4DA398;
extern unsigned __int8 byte_4DA3A8;
extern unsigned __int8 byte_4DA3B8;
extern unsigned __int8 byte_4DA3C8;
extern unsigned __int8 byte_4DA3D8;
extern unsigned __int8 byte_4DA3E8;
extern unsigned __int8 byte_4DA3F8;
extern unsigned __int8 byte_4DA408;
extern unsigned __int8 byte_4DA418;
extern unsigned __int8 byte_4DA428;
extern unsigned __int8 byte_4DA438;
extern unsigned __int8 byte_4DA448;
extern unsigned __int8 byte_4DA458;
extern unsigned __int8 byte_4DA468;
extern unsigned __int8 byte_4DA478;
extern unsigned __int8 byte_4DA488;
extern unsigned __int8 byte_4DA498;
extern unsigned __int8 byte_4DA4A8;
extern unsigned __int8 byte_4DA4B8;
extern unsigned __int8 byte_4DA4C8;
extern unsigned __int8 byte_4DA4D8;
extern unsigned __int8 byte_4DA4E8;
extern unsigned __int8 byte_4DA4F8;
extern unsigned __int8 byte_4DA508;
extern unsigned __int8 byte_4DA518;
extern unsigned __int8 byte_4DA528;
extern unsigned __int8 byte_4DA538;
extern unsigned __int8 byte_4DA548;
extern unsigned __int8 byte_4DA558;
extern unsigned __int8 byte_4DA568;
extern unsigned __int8 byte_4DA578;
extern unsigned __int8 byte_4DA588;
extern unsigned __int8 byte_4DA598;
extern unsigned __int8 byte_4DA5A8;
extern unsigned __int8 byte_4DA5B8;
extern unsigned __int8 USTAIRS;
extern unsigned __int8 WARPSTAIRS;
extern unsigned __int8 CRUSHCOL;
extern unsigned __int8 byte_4DA658;
extern unsigned __int8 byte_4DA668;
extern unsigned __int8 byte_4DA678;
extern unsigned __int8 byte_4DA680;
extern unsigned __int8 byte_4DA688;
extern unsigned __int8 byte_4DA698;
extern unsigned __int8 byte_4DA6A0;
extern unsigned __int8 byte_4DA6A8;
extern unsigned __int8 byte_4DA6B8;
extern unsigned __int8 BIG10;
extern unsigned __int8 byte_4DA6D4;
extern unsigned __int8 byte_4DA6D8;
extern unsigned __int8 byte_4DA6DC;
extern unsigned __int8 byte_4DA6E0;
extern unsigned __int8 byte_4DA6E4;
extern unsigned __int8 byte_4DA6E8;
extern unsigned __int8 byte_4DA6EC;
extern unsigned __int8 byte_4DA6F0;
extern unsigned __int8 byte_4DA710;
extern unsigned __int8 byte_4DA730;
extern unsigned __int8 byte_4DA748;
extern unsigned __int8 byte_4DA760;
extern unsigned __int8 byte_4DA778;
extern unsigned __int8 byte_4DA790;
extern unsigned __int8 byte_4DA7A8;
extern unsigned __int8 byte_4DA7C0;
extern BYTE CTRDOOR8[20];
extern int Patterns[100][10];
extern int (*dword_4DB908)(void);
extern int ThemeGood[4];
extern int trm5x[25];
extern int trm5y[25];
extern int trm3x[9];
extern int trm3y[9];
extern int sync_dword_4DBB1C;
extern int sgnSyncPInv;
extern int InvItemWidth[166];
extern int InvItemHeight[166];
extern char frameflag;
extern int frameend;
extern int framerate;
extern int scrollrt_4DC21C_soff;
extern int gamma_correction;
extern UINT gdwPalEntries;
extern int fullscreen;
extern int drawpanflag;
extern int Xshow_intro;
extern int visiondebug;
extern int light4flag;
extern int leveldebug;
extern int monstdebug;
extern int setseed;
extern int debugmonsttypes;
extern int PauseMode;
extern int FriendlyMode;
extern int sgnTimeoutCurs;
extern char sgbMouseDown;
extern char *spszMsgTbl[4];
extern char *spszMsgKeyTbl[4];
extern int WarpDropX[4];
extern int WarpDropY[4];
extern int deltaload;
extern char gbBufferMsgs;
extern int dword_4DCFB0;
extern char L5ConvTbl[16];
extern int WorldBoolFlag;
extern int gdwCurrentMask;
extern BYTE *gpCelFrame;
extern unsigned int *gpDrawMask;
extern unsigned int RightMask[32];
extern unsigned int LeftMask[64];
extern int WorldTbl3x16[48];
extern int WorldTbl17_1[17];
extern int WorldTbl17_2[17];
extern _UNKNOWN unk_4E00D0;
extern _UNKNOWN unk_4E0110;
extern char byte_4E0150[];
extern char byte_4E0160[16];
extern char byte_4E0170[16];
extern char byte_4E0180[256];
extern _UNKNOWN unk_4E0280;
extern _UNKNOWN unk_4E0548;
extern _UNKNOWN unk_4E0588;
extern _UNKNOWN unk_4E05C8;
extern _UNKNOWN unk_4E05D8;
extern _UNKNOWN unk_4E05F8;
extern _UNKNOWN unk_4E0608;
extern _UNKNOWN unk_4E0618;
extern _UNKNOWN unk_4E0718;
extern _UNKNOWN unk_4E0916;
extern int MissileFileFlag;
extern int monstkills[200];
extern int monstactive[200];
extern int nummonsters;
extern MonsterStruct monster[200];
extern int totalmonsters;
extern CMonster Monsters[16];
extern BYTE monster_4ED398[17][16];
extern int monstimgtot;
extern int uniquetrans;
extern char error_buf[];
extern __int16 gendung_4ED5B0[2048];
extern char nTransTable[2049];
extern int dMonster[112][112];
extern BYTE dungeon[40][40];
extern char dObject[112][112];
extern void *pSpeedCels;
extern int dword_4FE8FC;
extern char pdungeon[40][40];
extern char dDead[112][112];
extern SHORT dpiece_defs_map_1[12544][16];
extern char dTransVal2[112][112];
extern char TransVal;
extern int gendung_567144;
extern char Xdflags_2[40][40];
extern int dPiece[112][112];
extern char dTransVal[112][112];
extern int setloadflag_2;
extern int gendung_576C90[2048];
extern WORD *pMegaTiles;
extern void *pLevelPieces;
extern char block_lvid[2049];
extern char dung_map[112][112];
extern char nTrapTable[2049];
extern char leveltype;
extern BYTE currlevel;
extern BYTE TransList[256];
extern char nSolidTable[2049];
extern int gendung_57D6B8[2048];
extern ScrollStruct ScrollInfo;
extern void *pDungeonCels;
extern int speed_cel_frame_num_from_light_index_frame_num[16][128];
extern char dPlayer[112][112];
extern int gendung_5847D0_unused;
extern int gendung_5847D4_unused;
extern int scr_pix_width;
extern int scr_pix_height;
extern char dArch[112][112];
extern char nBlockTable[2049];
extern BYTE *level_special_cel;
extern char dFlags[112][112];
extern char dItem[112][112];
extern char setlvlnum;
extern int gendung_58E2F0[2048];
extern char nMissileTable[2049];
extern void *pSetPiece_2;
extern char setlevel;
extern int LvlViewY;
extern int LvlViewX;
extern int dmaxx;
extern int dmaxy;
extern int setpc_h;
extern int setpc_w;
extern int setpc_x;
extern int ViewX;
extern int ViewY;
extern int setpc_y;
extern char dMissile[112][112];
extern int dminx;
extern int dminy;
extern WORD dpiece_defs_map_2[112][112][16];
extern int qtexty;
extern int minitext_5F5C44;
extern char *qtextptr;
extern int sgLastScroll;
extern int qtextflag;
extern void *pMedTextCels;
extern BYTE *pTextBoxCels;
extern PATHNODE path_nodes[300];
extern int gdwCurPathStep;
extern int gdwCurNodes;
extern int pnode_vals[25];
extern PATHNODE *pnode_ptr;
extern PATHNODE *pnode_tblptr[300];
extern PATHNODE *path_2_nodes;
extern LPDIRECTSOUND sglpDS;
extern TSnd *sound_file[4];
extern BYTE *pDurIcons;
extern BYTE *pChrButtons;
extern int drawhpflag;
extern int dropGoldFlag;
extern int panbtn[6];
extern int control_5FDBA8_frame;
extern int control_5FDBAC_frame;
extern int chrbtn[4];
extern BYTE *pMultiBtns;
extern BYTE *pPanelButtons;
extern BYTE *pChrPanel;
extern int lvlbtndown;
extern int dropGoldValue;
extern int drawmanaflag;
extern int chrbtnactive;
extern void *pPanelText;
extern int talkbtndown[4];
extern int frame_gold;
extern BYTE *pLifeBuff;
extern BYTE *pBtmBuff;
extern int pstrjust[4];
extern int pnumlines;
extern int pinfoflag;
extern int pSpell;
extern BYTE *pManaBuff;
extern char infoclr;
extern int sgbPlrTalkTbl;
extern BYTE *pGBoxBuff;
extern BYTE *pSBkBtnCel;
extern char tempstr[256];
extern char sgszTalkMsg[80];
extern int sbooktab;
extern int pSplType;
extern int frame;
extern int initialDropGoldIndex;
extern int talkflag;
extern char *pSBkIconCels;
extern int sbookflag;
extern int chrflag;
extern int drawbtnflag;
extern BYTE *pSpellBkCel;
extern char infostr[260];
extern int numpanbtns;
extern char *pStatusPanel;
extern char panelstr[4][64];
extern int panelflag;
extern char Xspelltrans[];
extern int initialDropGoldValue;
extern char *Trans;
extern int panbtndown;
extern char *pTalkPanel;
extern char byte_5FE0D0;
extern int dword_5FE0D8[4];
extern BYTE byte_5FE0E8;
extern int dword_5FE0F0[];
extern struct _RTL_CRITICAL_SECTION stru_5FE100;
extern char byte_5FE118;
extern int gdwTurnsInTransit;
extern int dword_5FE120[];
extern int dword_5FE130;
extern int dword_5FE134;
extern int dword_5FE138;
extern int dword_5FE13C;
extern char sgbSyncCountDown;
extern char byte_5FE144;
extern char sgbPacketCountDown;
extern char sgbThreadIsRunning;
extern int gdwLargestMsgSize;
extern int gdwNormalMsgSize;
extern int dword_5FE158;
extern BYTE plr_msg_slot;
extern _plrmsg plr_msgs[8];
extern char pbMsg;
extern __int16 sgwPackPlrOffsetTbl[4];
extern char netplr[3928];
extern char msg_5FF8B0_plractive[4];
extern char msg_5FF8B4_isprocessing;
extern int cur_turn;
extern int dword_5FF8BC;
extern BYTE gbActivePlayers;
extern char gbGameDestroyed;
extern char multi_5FF8C8_hasdelta[4];
extern char packet_5FF8D0[];
extern char packet_5FFCD8[];
extern unsigned int Xmulti_mon_ai_seed;
extern BYTE gbMaxPlayers;
extern int s;
extern char sgbTimeout;
extern BYTE *sgpBackCel;
extern int sgdwProgress;
extern int progress_id;
extern LONG lDistanceToMove;
extern char mpq_buf[4096];
extern _HASHENTRY *sgpHashTbl;
extern _BLOCKENTRY *sgpBlockTbl;
extern int itemactive[127];
extern int uitemflag;
extern int itemavail[128];
extern ItemStruct curruitem;
extern ItemStruct item[127];
extern int itemhold[3][3];
extern void *Item2Frm[31];
extern int numitems;
extern int UniqueItemFlag[128];
extern _SNETVERSIONDATA fileinfo;
extern int gbActive;
extern IDirectDraw *lpDD;
extern CHAR diablo_exe_path[260];
extern char patch_rt_mpq_path[];
extern int dword_60D1DC;
extern WNDPROC CurrentProc;
extern LPDIRECTDRAWPALETTE lpDDPalette;
extern IDirectDrawSurface *lpDDSPrimary;
extern int diabdat_mpq;
extern BYTE *gpBuffer;
extern char diabdat_mpq_path[];
extern int patch_rt_mpq;
extern int stextup;
extern int storenumh;
extern int stextlhold;
extern ItemStruct boyitem;
extern int stextshold;
extern ItemStruct premiumitem[6];
extern BYTE *pSTextBoxCels;
extern int premiumlevel;
extern STextStruct stext[24];
extern char stextsize;
extern int stextsmax;
extern int InStoreFlag;
extern ItemStruct storehold[40];
extern ItemStruct witchitem[20];
extern int stextscrl;
extern int numpremium;
extern ItemStruct healitem[20];
extern ItemStruct golditem;
extern char storehidx[40];
extern BYTE *pSTextSlidCels;
extern int stextvhold;
extern int stextsel;
extern char stextscrldbtn;
extern BYTE *pCelBuff;
extern int stextsval;
extern ItemStruct smithitem[20];
extern int stextdown;
extern char stextscrlubtn;
extern char stextflag;
extern char hero_names[20][32];
extern char FileName[];
extern int dword_6180EC;
extern LightListStruct VisionList[32];
extern BYTE lightactive[32];
extern LightListStruct LightList[32];
extern int numlights;
extern BYTE dung_map_radius[16][128];
extern int dovision;
extern int numvision;
extern char lightmax;
extern int dolighting;
extern BYTE dung_map_rgba[8][8][16][16];
extern int visionid;
extern BYTE *pLightTbl;
extern char name[];
extern int mainmenu_61D640_unused;
extern int abyssx;
extern int missileactive[125];
extern int missilevail[125];
extern MissileStruct missile[125];
extern int nummissiles;
extern int ManashieldFlag;
extern int Xunusedmissiledata[125][3];
extern int MissilePreFlag;
extern int Xunusedmissileflag;
extern int dword_623430;
extern int dword_623438[17];
extern int dword_62343C[];
extern int dword_623480[4096];
extern BYTE *pSquareCel;
extern int help_select_line;
extern int help_62748C_num;
extern int helpflag;
extern XHelpStruct Xhelpstruct[8];
extern int help_6278F8_x;
extern int help_6278FC_y;
extern int help_627900_num;
extern XHelpStruct2 Xhelpstruct2[4];
extern int Xhelpflag_2;
extern int HelpTop;
extern int invflag;
extern BYTE *pInvCels;
extern int draw_btn;
extern int numtowners;
extern BYTE *pCowCels;
extern TownerStruct towner[];
extern __int16 automaptype[512];
extern int automap_628B38_x;
extern int automap_628B3C_y;
extern int automapflag;
extern char automap_628B48_xoff[31];
extern char automapview[40][40];
extern int AutoMapScale;
extern int AutoMapXOfs;
extern int AutoMapYOfs;
extern int AutoMapPosBits;
extern int AutoMapXPos;
extern int AutoMapYPos;
extern int AMPlayerX;
extern int AMPlayerY;
extern char msgflag;
extern char msgtable[80];
extern char msgdelay;
extern int trapid;
extern int trapdir;
extern void *pObjCels[40];
extern char ObjFileList[40];
extern int objectactive[127];
extern int nobjects;
extern int leverid;
extern int objectavail[127];
extern int numobjfiles;
extern ObjectStruct object[127];
extern int InitObjFlag;
extern int spurtndx;
extern DeadStruct dead[31];
extern int stonendx;
extern int sfxdelay;
extern int sfxdnum;
extern int sgbIsWalking;
extern int sgdwLastWalk;
extern int myplr;
extern PlayerStruct plr[4];
extern int deathflag;
extern int deathdelay;
extern int questlog;
extern BYTE *pQLogCel;
extern QuestStruct quests[11];
extern int qline;
extern int qlist[11];
extern int numqlines;
extern int Xmax_quests;
extern int WaterDone;
extern int ReturnLvlY;
extern int ReturnLvlX;
extern int ALLQUESTS;
extern BYTE *optbar_cel;
extern char gmenu_642C08;
extern BYTE *PentSpin_cel;
extern TMenuItem *sgpCurrItem;
extern BYTE *BigTGold_cel;
extern int gmenu_642C18;
extern char gmenu_byte_642C1C;
extern TMenuItem *gmenu_642C20_start;
extern BYTE *option_cel;
extern BYTE *sgpLogo;
extern int gmenu_642C2C;
extern int encrypt_table[1024];
extern int dword_643C30[256];
extern int trigflag;
extern int numtrigs;
extern TriggerStruct trigs[5];
extern int nSx1;
extern int nSx2;
extern int nSy1;
extern int nSy2;
extern int themeCount;
extern int nRoomCnt;
extern char predungeon[40][40];
extern ROOMNODE RoomList[81];
extern THEME_LOC themeLoc[50];
extern HALLNODE *pHallList;
extern int dword_645124;
extern char movie_playing;
extern int numthemes;
extern int ThemeGoodIn[3];
extern int themex;
extern int themey;
extern int themeVar1;
extern ThemeStruct themes[50];
extern SHA1Context sgSHA1[3];
extern WORD sync_word_6453F8[200];
extern int sync_dword_645588;
extern WORD sync_word_645590[200];
extern int cursor_dword_645720;
extern BYTE *cursor_dword_645724_buf2;
extern int cursH;
extern int icursH28;
extern int cursW;
extern int sgdwCursX;
extern int sgdwCursY;
extern int pcursmonst;
extern int dword_645740;
extern int dword_645744;
extern int icursW28;
extern BYTE *pCursCels;
extern int icursH;
extern char pcursinvitem;
extern int icursW;
extern char pcursitem;
extern int dword_645760;
extern int dword_645764;
extern int cursor_dword_645768_W;
extern int cursor_dword_64576C_H;
extern char sgSaveBack[8096];
extern char pcursobj;
extern char pcursplr;
extern int cursmx;
extern int cursmy;
extern int cursor_647720_last_pcursmont;
extern BYTE *cursor_dword_647724_buf1;
extern int pcurs;
extern int scrollrt_647730_off7;
extern int light_table_index;
extern int screen_y_times_768[1024];
extern int scrollrt_648738_line_off[480];
extern int scrollrt_648EB8_off4;
extern BYTE *gpBufEnd;
extern int scrollrt_648EC0_off3;
extern int scrollrt_648EC4_off8;
extern char arch_draw_type;
extern int scrollrt_648ECC_off9;
extern int cel_transparency_active;
extern int scrollrt_648ED4_off2;
extern int level_piece_id;
extern int scrollrt_648EDC_off1;
extern int scrollrt_648EE0_off6;
extern DWORD level_cel_block;
extern int mon_id;
extern int scrollrt_648EEC_off5;
extern int framestart;
extern PALETTEENTRY logical_palette[256];
extern PALETTEENTRY system_palette[];
extern PALETTEENTRY orig_palette[256];
extern char byte_649AF8;
extern int dword_649AFC;
extern int orgseed;
extern int sglGameSeed;
extern int SeedCount;
extern int dword_649B0C;
extern HWND ghMainWnd;
extern int glMid1Seed[18];
extern int glMid2Seed[17];
extern int gnLevelTypeTbl[17];
extern int MouseY;
extern int MouseX;
extern int glSeedTbl[17];
extern int dword_649C0C;
extern int dword_649C10;
extern int gbRunGame;
extern int gbRunGameResult;
extern int zoomflag;
extern int glEndSeed[17];
extern HINSTANCE ghInst;
extern int DebugMonster[10];
extern PortalStruct portal[4];
extern int portalindex;
extern int dword_649D20;
extern int sgnCurrMegaPlayer;
extern DLevel sgLevels[17];
extern char sbLastCmd;
extern TMegaPkt *sgpCurrPkt;
extern char sgRecvBuf[5813];
extern char byte_6635F0;
extern DJunk sgJunk;
extern TMegaPkt *sgpMegaPkt;
extern BYTE sgbDeltaChunks;
extern BYTE L5Dungeon[80][80];
extern char dflags[40][40];
extern int setloadflag;
extern int HR1;
extern int HR2;
extern int HR3;
extern int VR1;
extern int VR2;
extern int VR3;
extern void *pSetPiece;


